# Travis CI

language: php
dist: trusty
sudo: false
php:
- 7.2

before_script:
- cd /home/travis/build/
- echo | pecl install channel://pecl.php.net/yaml-2.0.2
- pecl install channel://pecl.php.net/crypto-0.3.1
- git clone https://github.com/pmmp/pthreads.git
- cd pthreads
- git checkout c8cfacda84f21032d6014b53e72bf345ac901dac
- phpize
- ./configure
- make
- make install
- cd ..
- echo "extension=pthreads.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

- mkdir PocketMine-MP
- cd PocketMine-MP
- export LATEST_RELEASE=$(curl -vs https://api.github.com/repos/pmmp/PocketMine-MP/releases/latest 2>&1 | grep browser_download_url | cut -d '"' -f 4)
- curl -O --location $LATEST_RELEASE
- mkdir -p plugins/BlockSniper

- cd /home/travis/build/

- cp -rf BlockHorizons/BlockSniper/tests PocketMine-MP/plugins/
- cp -rf BlockHorizons/BlockSniper/travis.php travis.php
- cp -rf BlockHorizons/BlockSniper PocketMine-MP/plugins

script:
- php travis.php

notifications:
  email:
    on_failure: always
    on_success: never
